version: '3'
services:
  api:
    build: .
    ports:
      - 8000:80
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: my-postgres
    volumes:
      - ./data:/var/lib/postgresql/data